# Server Settings
server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch Connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.ssl.verificationMode: "none"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true
xpack.monitoring.enabled: true

# Saved Objects Encryption
xpack.encryptedSavedObjects.encryptionKey: "12754b72d79043e273d9ac37da5103684608bc2bb5cd54d4ddb665adc85f4d7d"

# Logging Configuration
logging:
  root:
    level: info
    appenders: [default, file]
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: json

# Telemetry Settings
telemetry:
  optIn: false
  enabled: false